# run service and listen on this port
musicpd_service_listen_port: 6600

# publish service info with zeroconf/avahi
musicpd_publish_service_with_avahi: false

# set published avahi server name (%h expands to hostname)
musicpd_avahi_mpd_server_name: 'Music Player Daemon @ %h'

