- name: "Start 'musicpd' service, and enable it to start on boot"
  ansible.builtin.service:
    name: mpd_user_svc
    state: started
    enabled: true
  changed_when: false
  become: true
  become_user: root

