- name: "Configure MPD sound output"
  ansible.builtin.include_tasks: output/main.yml

- name: "Configure all MPD settings"
  ansible.builtin.include_tasks: settings/main.yml

- name: "Start and enable MPD service"
  ansible.builtin.include_tasks: service/main.yml

