- name: "Create OS-specific custom service files"
  ansible.builtin.include_tasks: create_service/main.yml

- name: "Stop MPD service, prior to config tasks"
  ansible.builtin.include_tasks: stop_service/main.yml

- name: "Configure OS-specific custom service files"
  ansible.builtin.include_tasks: config_service/main.yml

- name: "Create MPD user config directories"
  ansible.builtin.include_tasks: create_dirs/main.yml

- name: "Write all MPD settings to the config file"
  ansible.builtin.include_tasks: write_settings/main.yml

- name: "Start and enable MPD service"
  ansible.builtin.include_tasks: start_service/main.yml

